owner: ENDlezZenith
repo: status

sites:
  - name: IIS
    url: endzz.eu.org
    port: 8443
    check: "tcp-ping"
  - name: Cloud Disk
    url: endzz.eu.org
    port: 8444
    check: "tcp-ping"
  - name: Multimedia System
    url: endzz.eu.org
    port: 8445
    check: "tcp-ping"
  - name: Prometheus
    url: endzz.eu.org
    port: 8446
    check: "tcp-ping"
  # - name: Minecraft Server
  #   url: endzz.eu.org
  #   port: 25565
  #   check: "tcp-ping"
  # - name: Minecraft Map
  #   url: endzz.eu.org
  #   port: 25575
  #   check: "tcp-ping"

status-website:
  cname: status.endzz.eu.org
  logoUrl: https://raw.githubusercontent.com/ENDlezZenith/status/gh-pages/ENDZZ-Flanger.png
  name: ENDlezZenith Dashboard
  introTitle: ENDzZ Server Status Page
  introMessage: Check the status for all self-hosted services here.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ENDlezZenith
