owner: ENDlezZenith
repo: status

sites:
  - name: IIS
    url: endzz.eu.org
    icon: https://www.microsoft.com/favicon.ico
    port: 8443
    check: "tcp-ping"
  - name: Cloud Disk
    url: endzz.eu.org
    icon: https://doc.oplist.org/favicon.svg
    port: 8444
    check: "tcp-ping"
  - name: Multimedia System
    url: endzz.eu.org
    icon: https://jellyfin.org/images/favicon.ico
    port: 8445
    check: "tcp-ping"
  - name: Prometheus
    url: endzz.eu.org
    icon: https://prometheus.io/icon.svg
    port: 8446
    check: "tcp-ping"

status-website:
  cname: status.endzz.eu.org
  logoUrl: https://raw.githubusercontent.com/ENDlezZenith/status/master/assets/Favicon.png
  name: ENDzZ's Dashboard
  introTitle: Status
  introMessage: Check the status for all self-hosted services here.
  favicon: https://raw.githubusercontent.com/ENDlezZenith/status/master/assets/Favicon.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ENDlezZenith
